INSERT INTO USER (ID, FIRST_NAME, LAST_NAME) VALUES (1, 'Adam', 'Smith');
INSERT INTO USER (ID, FIRST_NAME, LAST_NAME) VALUES (2, 'Mario', 'Rossi');


INSERT INTO MEAL (ID, TEXT, NUMBER_OF_CALORIES) VALUES (1, 'meat', 10 );
INSERT INTO MEAL (ID, TEXT, NUMBER_OF_CALORIES) VALUES (2, 'apple', 20);

INSERT INTO USER_MEALS (ID, USER_ID, MEAL_ID, UPDATED_AT) VALUES (1, 1, 1, '2018-04-08');
INSERT INTO USER_MEALS (ID, USER_ID, MEAL_ID, UPDATED_AT) VALUES (2, 1, 2, '2018-04-08');
INSERT INTO CALORIES_PER_USER (ID, USER_ID, NUMBER_OF_CALORIES) VALUES (1, 1, 100);