CREATE SCHEMA DEMO;
CREATE TABLE DEMO.MEAL
(
    id int AUTO_INCREMENT PRIMARY KEY,
    text text,
    date DATE default NOW(),
    number_of_calories int default 0 not null
);

INSERT INTO DEMO.MEAL (ID, TEXT, NUMBER_OF_CALORIES, DATE) VALUES (1, 'meat', 0, '2018-04-08');
INSERT INTO DEMO.MEAL (ID, TEXT, NUMBER_OF_CALORIES, DATE) VALUES (2, 'apple', 0, '2018-04-08');
